wandb_version: 1

env_id:
  desc: null
  value: resource-gathering-v0
learning_rate:
  desc: null
  value: 0.1
gamma:
  desc: null
  value: 0.9
initial_epsilon:
  desc: null
  value: 1.0
final_epsilon:
  desc: null
  value: 0.05
epsilon_decay_steps:
  desc: null
  value: 100000
scalarization:
  desc: null
  value: weighted_sum
use_gpi_policy:
  desc: null
  value: true
weight_selection_algo:
  desc: null
  value: gpi-ls
epsilon_ols:
  desc: null
  value: null
transfer_q_table:
  desc: null
  value: true
dyna:
  desc: null
  value: true
dyna_updates:
  desc: null
  value: 5
gpi_pd:
  desc: null
  value: true
seed:
  desc: null
  value: null
algo:
  desc: null
  value: MultiPolicy MO Q-Learning
_wandb:
  desc: null
  value:
    code_path: code/morl/resource_gathering/mpmoq_policy.py
    python_version: 3.11.9
    cli_version: 0.17.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725090547
    t:
      1:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.9
      5: 0.17.7
      8:
      - 5
      13: linux-x86_64
